version: '3.8'

services:
  laravel:
    container_name: "laravel"
    build: 
      context: ./docker/php
    volumes:
      - .:/var/www/html
  
  nginx:
    image: nginx:1.25
    container_name: "nginx"
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel

  mysql:
    platform: linux/x86_64
    image: mysql:8.1
    container_name: "mysql"
    ports:
      - "3306:3306"
    restart: always


