version: '3.8'

services:
  laravel:
    container_name: "laravel"
    build: 
      context: ./docker/laravel
    ports:
      - "5173:5173"
    volumes:
      - .:/var/www/html
  
  nginx:
    image: nginx:1.25
    container_name: "nginx"
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel

  mysql:
    platform: linux/x86_64
    image: mysql:8.1
    container_name: "mysql"
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    restart: always


